spring.application.name=barber-app-backend

# Importar o arquivo de segredos
spring.config.import=optional:classpath:secrets.properties

# Conexão Supabase
spring.datasource.url=jdbc:postgresql://db.gyonpvxdnuwdqfyvglzb.supabase.co:6543/postgres?sslmode=require&prepareThreshold=0


spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações JWT
jwt.secret=${JWT_SECRET:8f8a35cc6e5893d987e92ce0397ee4a17a414b5182046bc322a317926adbe4fa}
jwt.expiration=86400000
